apiVersion: v1
kind: Secret
metadata:
  name: connector-config
type: Opaque
stringData:
  #REPLACE placeholders!
  OTLP_HEADER_AUTHORIZATION: "<YOUR-OPTIONAL-OTLP-HEADER-AUTHORIZATION>"
  OTLP_ENDPOINT: "<YOUR-OTLP-TARGET-ENDPOINT>"
  AWS_IdentityKey: "<YOUR-AWS-IDENTITY-KEY>"
  AWS_SecretKey: "<YOUR-AWS-SECRET-KEY>"
  PollingIntervalMinutes: "2"  

